DEV_DB_NAME: mohammed_ecommerce_development
DEV_DB_USER: khoadam
DEV_DB_PASSWORD: password

TEST_DB_NAME: mohammed_ecommerce_test
TEST_DB_USER: khoadam
TEST_DB_PASSWORD: password

PRODUCTION_DB_NAME: mohammed_ecommerce_production
PRODUCTION_DB_USER: khoadam
PRODUCTION_DB_PASSWORD: pass